CREATE TABLE IF NOT EXISTS `account` (
    username VARCHAR(250) NOT NULL PRIMARY KEY,
    password VARCHAR(250) NOT NULL,
    isSigned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS `movie` (
    title VARCHAR(250) NOT NULL PRIMARY KEY,
    genre VARCHAR(250) NOT NULL,
    runtime INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `room` (
    name VARCHAR(250) NOT NULL PRIMARY KEY,
    numberOfRows INT NOT NULL,
    numberOfCols INT NOT NULL
);