CREATE TABLE IF NOT EXISTS `movie` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    genre VARCHAR(250) NOT NULL,
    runtime INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `room` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    numberOfRows INT NOT NULL,
    numberOfCols INT NOT NULL
);